FROM docker.io/archlinux:latest

COPY host-mirrorlist /tmp/host-mirrorlist

RUN if [ -s /tmp/host-mirrorlist ]; then \
        cp /tmp/host-mirrorlist /etc/pacman.d/mirrorlist; \
    fi

RUN pacman-key --init && \
    pacman-key --populate archlinux && \
    pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
        @PACKAGES@ && \
    pacman -Scc --noconfirm


RUN useradd --create-home --shell /bin/bash someone && \
    mkdir -p /etc/sudoers.d && \
    printf '%s\n' 'someone ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/someone && \
    chmod 0440 /etc/sudoers.d/someone && \
